# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Patricia Cañadas' github.io sites
author: Patricia Cañadas # Author Name
email: pcanadas15@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My projects...
baseurl: /brown-orange-jekyll-theme # the subpath of your site, e.g. /blog
url: pcanadas.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 
github_username:  pcanadas
show_downloads: false
google_analytics:

# Build settings
highlighter: rouge
#timezone: Europe/Madrid
encoding: UTF-8
theme: brown-orange-jekyll-theme

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Default Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache

lsi: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
